name: PHP Composer

on:
  push:
    branches: [ patch1 ]
  pull_request:
    branches: [ patch1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          tools: composer, phpstan
          coverage: none
          extensions: :opcache
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: update autoload or Install dependencies
        run: (test -d vendor && (composer dump-autoload)) || (composer install --prefer-dist --no-progress --no-dev --ignore-platform-reqs)

      - name: phpstan test
        run: phpstan analyze --no-progress --memory-limit=2G

      - name: Build source code
        run: php -dphar.readonly=0 ./build/make-phar.php

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: PHAR
          path: ./JoinQuitSendActionbar.phar
